language: r
cache: packages
warnings_are_errors: false
sudo: false
compiler:
  - gcc
install:
- CXX="g++-4.8" CC="gcc-4.8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
