language: r
cache: packages
warnings_are_errors: false
sudo: required
dist: trusty

compiler:
  - gcc

r_binary_packages:
  - covr

after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
