language: r
cache: packages
warnings_are_errors: false
sudo: required
dist: trusty

compiler:
  - gcc

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
